### ISSUE TITLE
Support new discord features

### ISSUE THREAD

**Issue by WeeskyBDW** [Akasuki-bot/Akasuki#17]
Support new discord features like slash commands and thread, and why not buttons and select menus

**Comment by Dawoox** [comment]
Slash commands and buttons will be use in a near (or not) futur depending of the usage i can find for them
Select menus and thread will be added when Discord4J 3.2.x version roll out in stable release (and not dev as it is by now)

**Comment by WeeskyBDW** [comment]
D4j is currently in 3.2.0 RC3 so 3.2 will be soon (soon for d4j, in 1 or 2 month lol)

**Comment by WeeskyBDW** [comment]
> Slash commands and buttons will be use in a near (or not) futur depending of the usage i can find for them
Imo you can replace all commands by slash commands

**Comment by Dawoox** [comment]
> D4j is currently in 3.2.0 RC3 so 3.2 will be soon (soon for d4j, in 1 or 2 month lol)

1 or 2 months, so we don't need to talk about it rn

**Comment by Dawoox** [comment]
> > Slash commands and buttons will be use in a near (or not) futur depending of the usage i can find for them
> > Imo you can replace all commands by slash commands

I could but you could also dev BeYou-Bot but you choose to open issue about that, and like what i've say in the first message slash commands will be use in a near futur, i just want to update all things in one big patch when discord4j 3.2.0 roll-out

**Comment by WeeskyBDW** [comment]
Discord4J 3.2 was release. Any news about new discord features in Akatsuki ?

**Comment by Dawoox** [comment]
In v3-master we are now using slashs commands, more will come in the near futur

**Comment by Dawoox** [comment]
New features coming with the v4 release, issue closed as slash commands will now be the only way to interact with the bot
